### PR TITLE
Make sleep between downloads customizable again.

### PR DESCRIPTION
**Pull request by amandasaurus**
This was removed in commit fd804d91

### CODE REVIEW

**Comment by rory** [comment]
Hello, is there any chance to merge this?

**Comment by rory** [comment]
Hello, is it possible to merge this? Is there anything missing?

**Comment by rory** [comment]
Hi. Anything wrong with merging this and restoring this feature?

**Comment by rory** [comment]
Hello again, anything wrong with merging this?

**Comment by amandasaurus** [comment]
No updates. I'm closing this

**Pull request closed without merging**
